### ISSUE TITLE
onboard https://console-openshift-console.apps.cluster-01.okd.on.massopen.cloud/ as an environment

### ISSUE THREAD

**Issue by goern** [b4mad/op1st-emea-b4mad#25]
### Additional context

As an OKD community member,
I want cluster-01 be managed by Operate First GitOps,
so that I can install ArgoCD and Tekton on it.

/kind feature
/priority critical-urgent
/cc @LorbusChris

### Steps

- [x] create `argocd-manager` ServiceAccount in `kube-system` namespace on cluster-01-okd @goern 
- [x] use https://github.com/b4mad/op1st-emea-b4mad/blob/main/docs/gitops.md to create cluster config for argocd on nostromo
- [ ] integrate with OCP oauth
  - [x]  provide/create github apop for oauth
  - [ ] which ocp group shall auth on argocd?
- [ ] determine RBAC
  - [ ] which group shall be argocd admin?

### Acceptance Criteria

- [x] an environment directory is present for cluster-01-okd
- [x] cluster-01-okd is available on [ArgoCD](https://openshift-gitops-server-openshift-gitops.apps.nostromo.erdgeschoss.b4mad.emea.operate-first.cloud/applications?showFavorites=false&proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=)
- [ ] https://github.com/okd-project/okd-coreos-pipeline is deployed to cluster-01-okd via argocd

### Relevant links

n/a

**Comment by LorbusChris** [comment]
Thank you so much for helping out with this!
We'll sort out the permissions you need, and hopefully get this rolling soon :) 

fyi @sherine-k @lmzuccarelli @aleskandro
