### ISSUE TITLE
cert for apiserver

### ISSUE THREAD

**Issue by durandom** [b4mad/op1st-emea-b4mad#62]
Trying to add a cert-manager managed cert for the apiserver, since my CLI login requires a `--insecure-skip-tls-verify` 

I think we need a similar `Certificate` resource like https://github.com/b4mad/op1st-emea-b4mad/blob/main/manifests/environments/phobos/default-ingress-certificate.yaml

Looking at the [docs](https://docs.openshift.com/container-platform/4.14/security/certificates/api-server.html)  and this blog: https://epam.github.io/edp-install/operator-guide/ssl-automation-okd/#configure-certificates

@goern did you ever try to add a cert to the API manager? And if not, do we have to add anything to google cloud DNS? IIRC the cert-manager can talk to google DNS to add the required TXT records for auth, right? So it should be sufficient to make the configuration on the cluster side.

Note to self: make sure to be able to login to the cluster with just the kubeadmin cert when messing with this :)

**Comment by goern** [comment]
implemented with 800e547e9281798bb56c92c2cdfb57de41e2c342 

@durandom wfm, pls tst. `vi ~/.kube/config` and `oc login ...` again.

feel free to reopen...
